# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9d2a68392bb03be6bd344fbd94c3e0d054739a62f6710a3ce4e5acd93cf439860859dd1ed32271df8e9f7f64ef26517f487f38feb3768fc314f2a3dd8ad048a6

test:
  secret_key_base: 6decd19e27d51643d3bfdc306be98eb007be3df5a207adfb9f0426fe428da86cb00b99581cf74f200002dc835f97796dd2adb64e9af17167a86cca2c4610881e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
